window:
  title: "Mein Alacritty Terminal"
  dimensions:
    columns: 100
    lines: 30
  opacity: 0.9
  # Comment in when on mac and you wanna use keybindings that require
  # the ALT key. If you can't type characters like { or [, see the
  # keybindings section.
  #option_as_alt: Both

colors:
  primary:
    background: '0x191919'
    foreground: '0xeaeaea'

  # ANSI
  normal:
    black: '0x000000'
    red: '0xff0000'
    green: '0x00a000'
    yellow: '0xffff00'
    blue: '0x0066ff'
    magenta: '0xff00ff'
    cyan: '0x00cfcf'
    white: '0xfffffa'

  bright:
    black: '0x808080'
    red: '0xff0000'
    green: '0x00ff00'
    yellow: '0xffff00'
    blue: '0x0000ff'
    magenta: '0xff00ff'
    cyan: '0x00ffff'
    white: '0xffffff'

font:
  normal:
    family: 'FiraCode Nerd Font'
    style: Regular
  bold:
    family: 'FiraCode Nerd Font'
    style: Bold
  italic:
    family: 'FiraCode Nerd Font'
    style: Italic
  bold_italic:
    family: 'FiraCode Nerd Font'
    style: Bold Italic

  size: 14

scrolling:
  history: 1000

key_bindings:
  - { key: F11, action: 'ToggleFullscreen' }
  - { key: F12, action: 'ToggleFullscreen' }


  # Mac-KeyBindings on OptionAsAlt
  # Comment in when on mac the option key should be interpreted as alt key.
  # Somehow this breaks all keybindings of the option key even when you set
  # it to OnlyLeft or OnlyRight. So we gotta set them again:
  #- { key: 23, mods: Alt,       chars: "["  }  # Alt+5 -> [
  #- { key: 22, mods: Alt,       chars: "]"  }  # Alt+6 -> [
  #- { key: 26, mods: Alt,       chars: "|"  } # Alt+7 -> |
  #- { key: 28, mods: Alt,       chars: "{"  } # Alt+8 -> {
  #- { key: 25, mods: Alt,       chars: "]"  } # Alt+9 -> }
  #- { key: 37, mods: Alt,       chars: "@"  } # Alt+L -> @
  #- { key: 26, mods: Alt|Shift, chars: "\\" } # Alt+9 -> }

cursor:
  style: Beam
